nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.1.cjs

npmScopes:
  plentymarkets:
    npmRegistryServer: 'https://npm.pkg.github.com'
    npmAuthToken: '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'