nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.3.cjs

npmScopes:
  plentymarkets:
    npmRegistryServer: 'https://npm.pkg.github.com'
    npmAuthToken: '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'
