name: Compliance
on: pull_request
jobs:
  changelog:
    name: Changelog updated
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Check if changelog is in diff
        run: |
          gh pr diff "$BRANCH" --name-only >> diff.txt
          grep -Fxq "docs/changelog/changelog_en.md" diff.txt
          cat diff.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ github.head_ref }}
