name: Linting (Commitlint)
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  lint:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: './.github/.node-version'
          cache: 'yarn'

      - name: Create NPMRC
        run: |
          echo "npmScopes:
                  plentymarkets:
                    npmRegistryServer: 'https://npm.pkg.github.com'
                    npmAuthToken: '${{ secrets.ORGA_PAT_CICD1_PACKAGE_READ_ONLY }}'
                  " >> ~/.yarnrc.yml

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Validate PR title
        run: echo "${{ github.event.pull_request.title }}" | npx commitlint
