name: New release app

on:
   release:
     types: [published]

permissions:
  contents: read
  packages: read

jobs:
  create-archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Compress repo to Tar
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          cwd: ./
          files: |
            ./
          outPath: pwa.tar.gz

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: zipped-artifact
          path: ${{ github.workspace }}/pwa.tar.gz

  send-archive:
    runs-on: ubuntu-latest
    needs: install-and-build-dependencies
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: zipped-artifact
          path: ./
      - name: Upload File
        id: upload
        uses: JantHsueh/upload-file-action@1.0
        with:
          url: "https://pwapublish.plentysystems.com/storeDefaultApplication"
          forms: '{ "token": "${{ secrets.URL_ENDPOINT_TOKEN }}" }'
          fileForms: '{ "file": "${{ github.workspace }}/pwa.tar.gz" }'

